### ISSUE TITLE
Sun path seems misaligned in comparison to time

### ISSUE THREAD

**Issue by PinkSerenity** [Rinloid/musk_rose_rd#2]
When using `/time set night`, the stars will begin to appear, but the sun will only start setting now. This takes just 30 seconds, since the sun moves much faster than it did before. As soon as it has completely disappeared from sight it will appear at the opposite side of the world again, rising quickly before stopping at approximately 45°. This means that it also gets pretty dark for only a second.

**Comment by Rinloid** [comment]
The sun moves oddly because of the time detection which fetches the time from the fog colour.  The game gives us nothing about the time, so that is unfortunately unfixable.  However, there is a method to use the frame time, but I’m not comfortable doing that since it makes your game not survival friendly.
